name: JSBridge
options:
  bundleIdPrefix: org.linusu
  deploymentTarget:
    macOS: '10.11' # https://github.com/yonaskolb/XcodeGen/issues/268
    iOS: '9.0'
targets:
  JSBridge:
    type: framework
    platform: [iOS, macOS]
    sources: Sources
    scheme: {}
    dependencies:
      - carthage: PromiseKit
