name: JSBridge
options:
  bundleIdPrefix: org.linusu
  deploymentTarget:
    macOS: '10.10'
    iOS: '9.0'
targets:
  JSBridge:
    type: framework
    platform: [iOS, macOS]
    sources: Sources
    scheme: {}
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    dependencies:
      - carthage: PromiseKit
